services:
  database:
    container_name: open-ums-database
    image: postgres:16.4-alpine
    volumes:
      - open-ums-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_ums

volumes:
  open-ums-data:
